### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by cvijayarenu** [cvijayarenu/SimpleToDo#1]
My app is complete please review it . /cc @codepathreview and @codepath

**Comment by nesquena** [comment]
Chandra,

Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a personalized code review for each submitted project once the bootcamp starts.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 5-10 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU). Navigate to [January 7th and dates onward](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Please make sure to **include the best number** to reach you at in the scheduled event? Look forward to chatting soon!

**Comment by cvijayarenu** [comment]
I have added the ability to store the items in SQLite.

**Comment by cvijayarenu** [comment]
I have added custom adaptor for the UI.

**Comment by nesquena** [comment]
Reviewed your updates, nice start! Look forward to chatting tomorrow.

**Comment by cvijayarenu** [comment]
Thanks.
